Add support for PYTHON_VERSION env variable.
netlify/build-image pull request #363
Opened 2019-12-30 19:56 UTC by duckinator

My attempt at implementing #362.

I wasn't able to test it, unfortunately, because steps 2 and/or 3 in the README seem to be incorrect. There's no `build` command available in the Docker image.

2020-04-30 01:00 UTC, duckinator commented
Resolved the conflicts due to Swift support being added.

2020-04-30 01:01 UTC, duckinator commented
I also have no idea what's up with this:

![Screenshot_20200429_210138](https://user-images.githubusercontent.com/39698/80661417-a0f11580-8a5c-11ea-8cd8-6018ac6fcd0f.png)

2020-04-30 21:49 UTC, vbrown608 commented
@duckinator it means that Netlify's backend engineering team was automatically notified that we need to review your PR. I'll take a look and follow up soon. Thanks for your contribution!

2020-05-01 01:05 UTC, vbrown608 requested changes
This is a nice improvement, thanks! One small comment about error handling but otherwise looking good.

For local testing - I'm able to run the `build` command in the Docker image as described by the README, though it errors with the following because of https://github.com/netlify/build-image/issues/402 
```
Version '--no-progress' not found - try `nvm ls-remote` to browse available versions.
```
Opening a PR to address that, in the meantime you can edit the last line of `test-tools/start-image.sh` as the submitter suggests.

If you're still having trouble, could you try making sure you've pulled the most recent version of the `netlify/build:xenial` image? I'm also happy to test the PR locally before merging :)

2020-05-01 01:05 UTC, vbrown608 commented on run-build-functions.sh
> -    source $HOME/python2.7/bin/activate
The Docker container this runs in only has python 2.7, 3.5, and 3.7 installed. If `PYTHON_VERSION` isn't one of those, we should do some error handling like we're doing  when the user tries to load the version from `runtime.txt`.

2020-05-15 15:17 UTC, duckinator commented
Rebased off `xenial`; gonna try to address @vbrown608's review now.

2020-05-15 15:35 UTC, duckinator commented
@vbrown608 I think this is ready for another look! :slightly_smiling_face:

2020-05-20 00:31 UTC, erans commented
+1 on being able to specify PYTHON_VERSION as an env var and (even more important to me) - being able to support Python 3.8!

2020-06-02 15:39 UTC, vbrown608 approved these changes
Sorry for the delay, tested this in our build system and it's looking good. Thanks for your contribution!

2020-06-02 16:25 UTC, erans commented
> Sorry for the delay, tested this in our build system and it's looking good. Thanks for your contribution!

Does it mean you can just control it via the env var or does it also mean there is Python 3.8 support?

2020-06-02 17:48 UTC, vbrown608 commented
This PR adds the ability to control the python version through an env var but it must still be a supported version. It doesn't add support for 3.8.

2020-06-02 17:48 UTC, merged

2021-11-20 09:27 UTC, revolter commented
This doesn't work :( I set `PYTHON_VERSION` to `3.7`, but it still uses `2.7`.

2021-11-20 16:13 UTC, revolter commented
Using

```toml
[build.environment]
  PYTHON_VERSION = "3.7"
```

in a `netlify.toml` file doesn't work either :(

https://app.netlify.com/sites/fastlane-docs-preview/deploys/61991e5e6689420008c5416c

2021-11-20 18:43 UTC, duckinator commented
@revolter the documentation says only 2.7 and 3.8 are supported: https://github.com/netlify/build-image/blob/focal/included_software.md#languages

It seems for Python this isn't installing the language runtime on-the-fly, it's letting you choose from two installed versions. And in this case, the docs imply 3.8 will be used by default. So just removing that entirely might be your best bet.

2021-11-20 18:44 UTC, duckinator commented
Although the fact that it claims to default to 3.8, but falls back to 2.7 if it can't find the specified version is... bizarre...

2021-11-20 18:57 UTC, revolter commented
> @revolter the documentation says only 2.7 and 3.8 are supported: focal/included_software.md#languages

This was merged in the branch `xenial`, so the correct documentation is this: https://github.com/netlify/build-image/blob/xenial/included_software.md#languages, so it is supported.