Bump Go to 1.7 and omit patch version
netlify/build-image pull request #713
Opened 2021-12-16 19:29 UTC by akahn

#### Summary

1. Bump to latest Go minor version
2. Omit the patch version. By omitting the patch version, the latest 1.7.x will be used, which helps ensure that security fixes are brought in automatically.

2021-12-16 19:46 UTC, mraerino commented on Dockerfile
> +ENV GIMME_GO_VERSION "1.7"
_did you mean `1.17`?_

2021-12-17 11:21 UTC, JGAntunes commented
Hey @akahn 👋 so, the way default version are currently working is a bit... complicated. See - https://github.com/netlify/pod-workflow/issues/253#issuecomment-916205113 - essentially, the default version set here will have little impact into what's running on the customer side given to the pinning taking place at the site level within Bitballoon. The current strategy is to usually have a match between what is being pinned by default now and what we install by default within the `build-image` (although it doesn't seem to be the case for Go 🤔), until we have a chance to actually address this problem as a whole.

2021-12-17 14:28 UTC, akahn commented on Dockerfile
> +ENV GIMME_GO_VERSION "1.7"
Yes, thank you.

2022-01-04 11:42 UTC, JGAntunes requested changes, later dismissed
Left a suggestion in order to improve our test coverage in this area @akahn 👍

Also, we have an automated CHANGELOG being generated based on the `release-please` process (which itself relies on commit messages following the conventional commit format) - https://github.com/netlify/build-image/blob/focal/CONTRIBUTING.md#developing. You might need to update the PR title/commit msg (for single commit PRs).

2022-01-04 11:42 UTC, JGAntunes commented on run-build-functions.sh
>    else
Wondering if we could add a test case for this @akahn? (i.e. https://github.com/netlify/build-image/blob/focal/tests/node/base.bats#L13-L18). For more info around our tests see - https://github.com/netlify/build-image/blob/focal/CONTRIBUTING.md#tests

2022-06-06 16:04 UTC, aitkenster approved these changes

2022-06-07 12:32 UTC, merged

2022-06-07 12:40 UTC, akahn commented
👏 👏 👏